package usermodule;

public class mainExp extends callingFuncExamp
{
	public static void main(String[] args) 
	{
		mainExp mainC = new mainExp();
		mainC.iteratingXML("<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE cXML SYSTEM \"http://xml.cXML.org/schemas/cXML/1.2.006/cXML.dtd\"><cXML payloadID=\"1480414400752.687439@nse.vinimaya.com\" xml:lang=\"en-US\" timestamp=\"2016-11-29T05:13:20\" version=\"1.2.006\"><Header><From> <Credential domain=\"DUNS\">      <Identity>159003651</Identity>      </Credential>    </From>    <To>      <Credential domain=\"NetworkId\">        <Identity>Y12</Identity>      </Credential>    </To>    <Sender>      <Credential domain=\"DUNS\">        <Identity>159003651</Identity>      </Credential>      <UserAgent>ViniSyndicate Catalog Integration System</UserAgent>    </Sender>  </Header>  <Message deploymentMode=\"production\">    <PunchOutOrderMessage>      <BuyerCookie>EIA79I8ZFX7Z</BuyerCookie>      <PunchOutOrderMessageHeader operationAllowed=\"edit\" quoteStatus=\"final\">        <Total>          <Money currency=\"USD\">44.49</Money>        </Total>      </PunchOutOrderMessageHeader>      <ItemIn quantity=\"1\">        <ItemID>          <SupplierPartID>PAP62145</SupplierPartID>          <SupplierPartAuxiliaryID>PAP62145</SupplierPartAuxiliaryID>        </ItemID>        <cartIdentifier>          <cartid>502476</cartid>        </cartIdentifier>        <ItemDetail>          <UnitPrice>            <Money currency=\"USD\">9.52</Money>          </UnitPrice>          <Description xml:lang=\"en\">PEN, FLAIR ULTRAFN,8 PK</Description>          <UnitOfMeasure>SET</UnitOfMeasure>          <Classification domain=\"UNSPSC\">44100000</Classification>          <LeadTime>1</LeadTime>          <ManufacturerPartID />          <ManufacturerName />          <Extrinsic name=\"HazardousMaterial\" />          <Extrinsic name=\"Radioactive\" />          <Extrinsic name=\"CAS\" />        </ItemDetail>        <SupplierID domain=\"DUNS\">228826</SupplierID>      </ItemIn>      <ItemIn quantity=\"1\">        <ItemID>          <SupplierPartID>HAM86700</SupplierPartID>          <SupplierPartAuxiliaryID>HAM86700</SupplierPartAuxiliaryID>        </ItemID>        <cartIdentifier>          <cartid>502476</cartid>        </cartIdentifier>        <ItemDetail>          <UnitPrice>            <Money currency=\"USD\">34.97</Money>          </UnitPrice>          <Description xml:lang=\"en\">8.5X11,20LB,30 RCYL,92BRT,GRT WHT</Description>          <UnitOfMeasure>CTN</UnitOfMeasure>          <Classification domain=\"UNSPSC\">44100000</Classification>          <LeadTime>1</LeadTime>          <ManufacturerPartID />          <ManufacturerName />          <Extrinsic name=\"HazardousMaterial\" />          <Extrinsic name=\"Radioactive\" />          <Extrinsic name=\"CAS\" />        </ItemDetail>        <SupplierID domain=\"DUNS\">228826</SupplierID>      </ItemIn>    </PunchOutOrderMessage>  </Message></cXML>");
		String s = getUntprc();
		System.out.println("Unit price in Main class : " + s );
	}
	
}
